# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggcode" do
  version "1.3.44"

  on_macos do
    on_intel do
      sha256 "2b66ba69bf39607046d7b24a4ee43dce6ad585e4df92f6d3cb5c9ca243fe0a7e"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a1a50dfe1ae3212948a37d8e8a894ada205bcec4883308ba546634e97bc9bbb2"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb92e9e209379a9ea601692b2bca990ab5b162f837ef0ea7c0debcea179c609d"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1c00c28615c5a839171a2d08ebc230ca0752cd293c5f3c2c4c1d13ee1568e3e9"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_arm64.tar.gz"
    end
  end

  name "ggcode"
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggcode"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ggcode"]
    end
  end

  # No zap stanza required

end
