# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggcode" do
  version "1.3.46"

  on_macos do
    on_intel do
      sha256 "d3225a24012ba621c0836f5b2abba812fb0c8b0130e3ed794e38aea42167a19c"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "223f6b6513ea15b93140cda888f30b807aa23f657661448a0b07c08fe149a5cb"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e3ca3c20878a3b62bc5e9d5e1bcf21846846f0bfdbb945c0b0ca8953a2c7b2b"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9c68facbf68fb0373268dc5c3289003df9a2cbddda867e7878a4d0d07b729a0a"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_arm64.tar.gz"
    end
  end

  name "ggcode"
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggcode"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ggcode"]
    end
  end

  # No zap stanza required

end
