# This file was generated by GoReleaser. DO NOT EDIT.
cask "ggcode" do
  version "1.3.39"

  on_macos do
    on_intel do
      sha256 "83acf8089906a856d33e4b5e9cfaee506564b90337a9012b7760e80efdf7ff0d"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d415c8c954914efd530371ff1d48b9b4efd6bd46fe7e64e2befee3da89aaa2a9"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46657571180881cf9513c28d274b061cd601f4536781ac9a08eb0adfa566608e"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "174e8efda47ebd6ae4459ef5cf84590640ace130c219deead06e737069ae85fa"
      url "https://github.com/topcheer/ggcode/releases/download/v#{version}/ggcode_linux_arm64.tar.gz"
    end
  end

  name "ggcode"
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ggcode"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ggcode"]
    end
  end

  # No zap stanza required

end
