# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggcode < Formula
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"
  version "1.3.67"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/topcheer/ggcode/releases/download/v1.3.67/ggcode_darwin_x86_64.tar.gz"
      sha256 "5364683e162c94c7c0f13f81714b1a16ab47ef096c060a9e623da20c0340ae28"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/topcheer/ggcode/releases/download/v1.3.67/ggcode_darwin_arm64.tar.gz"
      sha256 "4fad7693cd3497a21b2d51afb815c2a37d72c21f837356c35db824de35a0a755"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.3.67/ggcode_linux_x86_64.tar.gz"
      sha256 "5fb19cc9ee7e1241cc290992417f6219ff173d892b3964eb55c48880398079b3"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.3.67/ggcode_linux_arm64.tar.gz"
      sha256 "39197182c8f0ddf5bf11af7b7dbc793fe5d0802778e3899698e7c3db0b05762e"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end
end
