# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggcode < Formula
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"
  version "1.1.37"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.37/ggcode_darwin_x86_64.tar.gz"
      sha256 "fdb73b2af2267fa59ad2eb722abec122169dd3d2f0382d80df3bd49c5a904d68"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.37/ggcode_darwin_arm64.tar.gz"
      sha256 "ed4c8022c1d0bb9630e350b683516ecf3c653c37e73d17d34af2925da71dbd2a"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.37/ggcode_linux_x86_64.tar.gz"
      sha256 "c80e7ffaa12757eafe242020af6d32e521cf6d7a43c0b9e130a8c65cf39c9cb3"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.37/ggcode_linux_arm64.tar.gz"
      sha256 "e9d1c95080bd0b0870c4696c81688c87443fe04c14228b5ed4764a23754b26ff"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end

  test do
    system "#{bin}/ggcode", "--version"
  end
end
