# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggcode < Formula
  desc "AI coding agent for the terminal with TUI, MCP, and IM integrations."
  homepage "https://github.com/topcheer/ggcode"
  version "1.1.73"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.73/ggcode_darwin_x86_64.tar.gz"
      sha256 "1e423fa7a2571a39c5e96c9313917f4f70938cf7531b3dc5332903a4fa199c91"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.73/ggcode_darwin_arm64.tar.gz"
      sha256 "664538ddd0d4b3a487a3471a367622e00feccb8e3c18d0c9ec21e8dcd4f07a78"

      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.73/ggcode_linux_x86_64.tar.gz"
      sha256 "e4b87e4de2d002ed5c814c57f767fac0ee249a4dd36f417d4393adc1b307df3f"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/topcheer/ggcode/releases/download/v1.1.73/ggcode_linux_arm64.tar.gz"
      sha256 "155c944bb676aaffec1a12f435fee9635c092fefeefcdadebe05b8cdd83974bc"
      define_method(:install) do
        bin.install "ggcode"
      end
    end
  end

  test do
    system "#{bin}/ggcode", "--version"
  end
end
